name: Publish to Chrome Web Store

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Type of Release
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    name: Publish Extension to Chrome Web Store
    environment: production
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_RELEASE_PAT }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
        cache: npm

    - name: Bump version
      run: |
        version=$(npm --no-git-tag-version --tag-version-prefix="" version ${{ github.event.inputs.release_type }})
        mv src/manifest.json src/manifest.json.old
        jq --arg version $version '. + { version: $version, version_name: $version }' src/manifest.json.old > src/manifest.json
        rm src/manifest.json.old
        echo "version=$version" >> "$GITHUB_ENV"

    - name: Commit version bump
      uses: EndBug/add-and-commit@v9
      with:
        message: Bump version to ${{ env.version }}
        add: src/manifest.json package.json package-lock.json

    - name: Build
      run: |
        npm ci
        npm run build


    - name: Create GitHub release
      run: gh release create v${{ env.version }} --title "Store Release v${{ env.version }}" --generate-notes  release.zip
