name: Publish to Chrome Web Store

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Type of Release
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    name: Publish Extension to Chrome Web Store
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
        cache: npm

    - name: Bump version
      run: |
        version=$(npm --no-git-tag-version --tag-version-prefix="" version ${{ github.event.inputs.release_type }})
        mv src/manifest.json src/manifest.json.old
        jq --arg version $version '. + { version: $version, version_name: $version }' src/manifest.json.old > src/manifest.json
        rm src/manifest.json.old

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        file-path: release.zip
        extension-id: ${{ secrets.EXTENSION_ID }}
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        publish: false
