name: Publish to Stores

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Type of Release
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    name: 'Bump Version: ${{ github.event.inputs.release_type }}'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-version.outputs.version }}
      commit: ${{ steps.bump-version.outputs.commit }}
    env:
      GH_TOKEN: ${{ secrets.GH_RELEASE_PAT }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
        cache: npm

    - id: bump-version
      name: Bump version
      run: |
        version=$(npm --no-git-tag-version --tag-version-prefix="" version ${{ github.event.inputs.release_type }})
        mv src/manifest.json src/manifest.json.old
        jq --arg version $version '. + { version: $version, version_name: $version }' src/manifest.json.old > src/manifest.json
        rm src/manifest.json.old
        echo "version=$version" >> $GITHUB_ENV
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Create release commit
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        git add src/manifest.json package.json package-lock.json
        git commit -m "Bump version to ${{ env.version }}"

    - name: Push changes to main
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.GH_RELEASE_PAT }}
        branch: main
        unprotect_reviews: true

  publish-to-chrome:
    name: Publish to Chrome Web Store
    runs-on: ubuntu-latest
    environment: Chrome Web Store
    needs: bump-version
    env:
      VERSION: ${{ needs.bump-version.outputs.version }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
        cache: npm

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Upload to Chrome Web Store
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        file-path: release.zip
        extension-id: ${{ secrets.EXTENSION_ID }}
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}

    - name: Store Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: chrome-release
        path: release.zip

  publish-to-firefox:
    name: Publish to Firefox Add-ons
    runs-on: ubuntu-latest
    environment: Firefox Add-Ons
    needs: bump-version
    env:
      VERSION: ${{ needs.bump-version.outputs.version }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
        cache: npm

    - name: Build
      run: |
        npm ci
        npm run build:firefox

    - name: Upload to Firefox Add-ons
      uses: trmcnvn/firefox-addon@v1
      with:
        uuid: encypted-env-viewer@jordanwelch.com
        xpi: release.zip
        manifest: dist/manifest.json
        api-key: ${{ secrets.FIREFOX_API_KEY }}
        api-secret: ${{ secrets.FIREFOX_API_SECRET }}

    - name: Store Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: firefox-release
        path: release.zip

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - bump-version
      - publish-to-chrome
      - publish-to-firefox
    env:
      GH_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
      VERSION: ${{ needs.bump-version.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Download Chrome Release
        uses: actions/download-artifact@v2
        with:
          name: chrome-release
          path: chrome-release.zip

      - name: Download Firefox Release
        uses: actions/download-artifact@v2
        with:
          name: firefox-release
          path: firefox-release.xpi

      - name: Create GitHub release
        run: gh release create v$VERSION >
         --title "Store Release v$VERSION" >
         --generate-notes chrome-release.zip firefox-release.xpi
