name: Quality Check PR
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Run Lint
      run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test
